name: Build and Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and test
        run: |
          set -e
          # Example: compile and run each .cpp
          FILES=$(find src -name '*.cpp')
          for f in $FILES; do
            BIN=$(echo "$f" | sed 's|/|_|g' | sed 's|\.cpp$||').out
            echo "Compiling $f -> $BIN"
            g++ -std=c++14 "$f" -o "$BIN" -lpthread -lm
            echo "Running $BIN..."
            timeout 90s ./"$BIN"
            if [ $? -ne 0 ]; then
              echo "Failure in $f"
              exit 1
            fi
          done
          echo "All .cpp files compiled and ran successfully!"
