- name: Build and test
  run: |
    set -e

    # Step 1: Make a list of "library" .cpp (no main) and "test" .cpp (with main).
    LIB_SOURCES=""
    TEST_SOURCES=""

    for f in $(find src -name '*.cpp'); do
      # grep the file for main (this is naive—better to parse with something else).
      if grep -q 'int main' "$f"; then
        TEST_SOURCES="$TEST_SOURCES $f"
      else
        LIB_SOURCES="$LIB_SOURCES $f"
      fi
    done

    echo "Library sources: $LIB_SOURCES"
    echo "Test sources: $TEST_SOURCES"

    # Step 2: Compile library sources into objects
    mkdir -p build
    for libsrc in $LIB_SOURCES; do
      obj="build/$(basename $libsrc .cpp).o"
      echo "Compiling object for $libsrc -> $obj"
      g++ -std=c++14 -c "$libsrc" -o "$obj"
    done

    # Combine into a single library archive (optional)
    ar rcs build/libmylib.a build/*.o

    # Step 3: For each test source, compile + link with the library
    for testsrc in $TEST_SOURCES; do
      exe="build/$(basename $testsrc .cpp).out"
      echo "Building test executable $exe from $testsrc"
      g++ -std=c++14 "$testsrc" build/libmylib.a -o "$exe" -lm -lpthread
    done

    # Step 4: Run each test with a 90s timeout
    for exe in build/*.out; do
      echo "Running test $exe..."
      timeout 90s "$exe"
    done

    echo "All tests compiled and ran successfully!"
